### PR TITLE
Add reducer and action book store project

### PR DESCRIPTION
**Pull request by juaryimami**
### In this step:
---
-  I tied to configure my `Redux` Store and write actions and reducer for adding and removing books.
---
#### Thank you for reviewing my project!!!!.

### CODE REVIEW

**Comment by julie-ify** [comment]
Hi @juaryimami,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### 1. According to the requested gitflow, you should merge to the `develop` branch, not main branch. Kindly fix that.
### 2. Your readme describes the math magician project whereas this is a bookstore project. Kindly fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by juaryimami** [comment]
ohhh sorry, I will fix it soon.

**Review by sja-thedude — COMMENTED** [review]
## Invalid Code Review Request ❌

Hi @juaryimami, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that is been deleted, not correct gitflow.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by juaryimami** [comment]
Am repeating the module that's why am re submitting the PR that I get approved last time.

**Comment by rloterh** [comment]
Hi @juaryimami ,

If your project was previously approved, I suggest that you kindly submit the Pull Request that has the approval remarks for this project.

Cheers! 😃

**Comment by juaryimami** [comment]
so kindly please approved it again otherwise I cannot submit the project.

**Review by rloterh — COMMENTED** [review]
Hi Juhar, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect git-flow/ GitHub flow. Kindly note that the merge request for this activity should flow **from feature into development**. Kindly use the correct git-flow and request another code review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by juaryimami** [comment]
what you want me to do, should I create a new branch and create a new pull request. I can not understand what you code reviewer doing.

**Comment by mirouhml** [comment]
Hi @juaryimami , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR, that is closed, I understand that you have the project approved already, in that case, please submit [this PR](https://github.com/juaryimami/book-store-react/pull/3) instead of this one, since the project is already approved there.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit the link I mentioned 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by rloterh** [comment]
Hi @juaryimami,

Looking at the list of the (closed)Pull Requests related to this project, I can see that this was the PR for the same activity which was previously approved: 
[Pull Request 3](https://github.com/juaryimami/book-store-react/pull/3)

image

You should use [this PR link](https://github.com/juaryimami/book-store-react/pull/3) to submit your repeated project on the student dashboard. 

Feel free to let me know if you need further clarifications

**Comment by juaryimami** [comment]
Yes I am repeating this module due to material test failure not for
attendance or completing the task. So should I create anew repo for this
project?. The student success team told me not to redo the project for
those already get approved. What should I do?.

**Comment by rloterh** [comment]
@juaryimami 
Just resubmit your project using [this link](https://github.com/juaryimami/book-store-react/pull/3), under the same activity
and your project should be approved at once!

Cheers! 😃

**Comment by juaryimami** [comment]
Will do, thanks!

**Pull request closed without merging**
